# config/boot.rb

# -------------------------------------------------
# NOTE: This file is generated by `rails new`.
# It bootstraps the Rails environment and loads the
# gem dependencies defined in the Gemfile.
# -------------------------------------------------

# Load the Gemfile that lives one directory up (the root of the project).
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

# -------------------------------------------------
# Gem dependencies
# -------------------------------------------------
require "bundler/setup"      # Loads gems from the Gemfile and adds them to the load path.
require "rails"              # Bootstraps the Rails framework (loads all Rails engines, etc.).

# -------------------------------------------------
# Optional performance booster (Bootsnap)
# -------------------------------------------------
# Bootsnap dramatically reduces the time it takes to start a Rails app by
# caching compiled Ruby files, resolving constant lookups, and more.
# However, it is not a hard requirement – if it cannot be loaded for any
# reason (missing gem, incompatible Ruby version, etc.) we simply continue
# without it so the application can still start.
#
# The `begin … rescue LoadError` pattern ensures that a missing or broken
# Bootsnap installation does not prevent Rails from booting.
#
begin
  require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
rescue LoadError => e
  warn "Bootsnap not available: #{e.message}" if ENV['RAILS_ENV'] != 'test'
end

# -------------------------------------------------
# Application initialization
# -------------------------------------------------
# The rest of the initialization logic (e.g., loading environment variables,
# configuring the logger, setting up the application module, etc.) follows
# after this point.  It is left untouched because the modification only
# concerns the Bootsnap require.
#
# Example (generated by `rails new`):
#
# Rails.application.initialize!

# -------------------------------------------------
# End of file
# -------------------------------------------------